version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing app dependencies...
  build:
    commands:
      - echo Building static site...
      - echo Run tests...
