# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Step(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'bool',
        'answer': 'bool',
        'complete': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'answer': 'answer',
        'complete': 'complete'
    }

    def __init__(self, id=None, answer=None, complete=None):
        """
        Step - a model defined in Swagger
        """

        self._id = None
        self._answer = None
        self._complete = None

        if id is not None:
          self.id = id
        if answer is not None:
          self.answer = answer
        if complete is not None:
          self.complete = complete

    @property
    def id(self):
        """
        Gets the id of this Step.

        :return: The id of this Step.
        :rtype: bool
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Step.

        :param id: The id of this Step.
        :type: bool
        """

        self._id = id

    @property
    def answer(self):
        """
        Gets the answer of this Step.

        :return: The answer of this Step.
        :rtype: bool
        """
        return self._answer

    @answer.setter
    def answer(self, answer):
        """
        Sets the answer of this Step.

        :param answer: The answer of this Step.
        :type: bool
        """

        self._answer = answer

    @property
    def complete(self):
        """
        Gets the complete of this Step.

        :return: The complete of this Step.
        :rtype: bool
        """
        return self._complete

    @complete.setter
    def complete(self, complete):
        """
        Sets the complete of this Step.

        :param complete: The complete of this Step.
        :type: bool
        """

        self._complete = complete

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Step):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
