# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Student(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'teacher_id': 'int',
        'semester': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'teacher_id': 'teacher_id',
        'semester': 'semester'
    }

    def __init__(self, id=None, user_id=None, teacher_id=None, semester=None):
        """
        Student - a model defined in Swagger
        """

        self._id = None
        self._user_id = None
        self._teacher_id = None
        self._semester = None

        if id is not None:
          self.id = id
        if user_id is not None:
          self.user_id = user_id
        if teacher_id is not None:
          self.teacher_id = teacher_id
        if semester is not None:
          self.semester = semester

    @property
    def id(self):
        """
        Gets the id of this Student.

        :return: The id of this Student.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Student.

        :param id: The id of this Student.
        :type: int
        """

        self._id = id

    @property
    def user_id(self):
        """
        Gets the user_id of this Student.

        :return: The user_id of this Student.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this Student.

        :param user_id: The user_id of this Student.
        :type: int
        """

        self._user_id = user_id

    @property
    def teacher_id(self):
        """
        Gets the teacher_id of this Student.

        :return: The teacher_id of this Student.
        :rtype: int
        """
        return self._teacher_id

    @teacher_id.setter
    def teacher_id(self, teacher_id):
        """
        Sets the teacher_id of this Student.

        :param teacher_id: The teacher_id of this Student.
        :type: int
        """

        self._teacher_id = teacher_id

    @property
    def semester(self):
        """
        Gets the semester of this Student.

        :return: The semester of this Student.
        :rtype: datetime
        """
        return self._semester

    @semester.setter
    def semester(self, semester):
        """
        Sets the semester of this Student.

        :param semester: The semester of this Student.
        :type: datetime
        """

        self._semester = semester

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Student):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
