# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.problems_api import ProblemsApi


class TestProblemsApi(unittest.TestCase):
    """ ProblemsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.problems_api.ProblemsApi()

    def tearDown(self):
        pass

    def test_add_problem(self):
        """
        Test case for add_problem

        Add new problem
        """
        pass

    def test_delete_problem(self):
        """
        Test case for delete_problem

        Deletes a problem
        """
        pass

    def test_get_problem_by_id(self):
        """
        Test case for get_problem_by_id

        Find Problem by ID
        """
        pass

    def test_update_problem(self):
        """
        Test case for update_problem

        Update existing problem
        """
        pass


if __name__ == '__main__':
    unittest.main()
