# coding: utf-8

"""
    Test_4_Success

    API for Test4Success  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.quiz_api import QuizApi  # noqa: E501
from swagger_client.rest import ApiException


class TestQuizApi(unittest.TestCase):
    """QuizApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.quiz_api.QuizApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_quiz(self):
        """Test case for add_quiz

        Add new quiz  # noqa: E501
        """
        pass

    def test_delete_quiz(self):
        """Test case for delete_quiz

        Deletes a quiz  # noqa: E501
        """
        pass

    def test_get_quiz_by_id(self):
        """Test case for get_quiz_by_id

        Find Quiz by ID  # noqa: E501
        """
        pass

    def test_update_quiz(self):
        """Test case for update_quiz

        Update existing quiz  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
