# coding: utf-8

"""
    Test_4_Success

    API for Test4Success  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.teachers_api import TeachersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeachersApi(unittest.TestCase):
    """TeachersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.teachers_api.TeachersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_teacher(self):
        """Test case for add_teacher

        Add new teacher  # noqa: E501
        """
        pass

    def test_delete_teacher(self):
        """Test case for delete_teacher

        Deletes a teacher  # noqa: E501
        """
        pass

    def test_get_teacher_by_id(self):
        """Test case for get_teacher_by_id

        Find Teacher by ID  # noqa: E501
        """
        pass

    def test_update_teacher(self):
        """Test case for update_teacher

        Update existing teacher  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
