# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.scores import Scores


class TestScores(unittest.TestCase):
    """ Scores unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScores(self):
        """
        Test Scores
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.scores.Scores()
        pass


if __name__ == '__main__':
    unittest.main()
