# coding: utf-8

"""
    Test_4_Success

    API for Test4Success  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.scores import Scores  # noqa: E501
from swagger_client.rest import ApiException


class TestScores(unittest.TestCase):
    """Scores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScores(self):
        """Test Scores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.scores.Scores()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
