# coding: utf-8

"""
    Test_4_Success

    API for Test4Success  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.score_api import ScoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScoreApi(unittest.TestCase):
    """ScoreApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.score_api.ScoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_score(self):
        """Test case for add_score

        Add new score  # noqa: E501
        """
        pass

    def test_delete_score(self):
        """Test case for delete_score

        Deletes a score  # noqa: E501
        """
        pass

    def test_get_score_by_id(self):
        """Test case for get_score_by_id

        Find Score by ID  # noqa: E501
        """
        pass

    def test_update_score(self):
        """Test case for update_score

        Update existing score  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
