# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.teachers_api import TeachersApi


class TestTeachersApi(unittest.TestCase):
    """ TeachersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.teachers_api.TeachersApi()

    def tearDown(self):
        pass

    def test_add_teacher(self):
        """
        Test case for add_teacher

        Add new teacher
        """
        pass

    def test_delete_teacher(self):
        """
        Test case for delete_teacher

        Deletes a teacher
        """
        pass

    def test_get_teacher_by_id(self):
        """
        Test case for get_teacher_by_id

        Find Teacher by ID
        """
        pass

    def test_update_teacher(self):
        """
        Test case for update_teacher

        Update existing teacher
        """
        pass


if __name__ == '__main__':
    unittest.main()
