# coding: utf-8

"""
    Test_4_Success

    API for Test4Success  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.problems_api import ProblemsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProblemsApi(unittest.TestCase):
    """ProblemsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.problems_api.ProblemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_problem(self):
        """Test case for add_problem

        Add new problem  # noqa: E501
        """
        pass

    def test_delete_problem(self):
        """Test case for delete_problem

        Deletes a problem  # noqa: E501
        """
        pass

    def test_get_problem_by_id(self):
        """Test case for get_problem_by_id

        Find Problem by ID  # noqa: E501
        """
        pass

    def test_update_problem(self):
        """Test case for update_problem

        Update existing problem  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
