# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """ UsersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.users_api.UsersApi()

    def tearDown(self):
        pass

    def test_add_user(self):
        """
        Test case for add_user

        Add new user to system
        """
        pass

    def test_delete_user(self):
        """
        Test case for delete_user

        Deletes a user
        """
        pass

    def test_get_user_by_id(self):
        """
        Test case for get_user_by_id

        Find User by ID
        """
        pass

    def test_update_user(self):
        """
        Test case for update_user

        Update existing user
        """
        pass


if __name__ == '__main__':
    unittest.main()
