# coding: utf-8

"""
    Test_4_Success

    API for Test4Success  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.step_api import StepApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStepApi(unittest.TestCase):
    """StepApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.step_api.StepApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_step(self):
        """Test case for add_step

        Add new step  # noqa: E501
        """
        pass

    def test_delete_step(self):
        """Test case for delete_step

        Deletes a step  # noqa: E501
        """
        pass

    def test_get_step_by_id(self):
        """Test case for get_step_by_id

        Find Step by ID  # noqa: E501
        """
        pass

    def test_update_step(self):
        """Test case for update_step

        Update existing step  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
