# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.teacher import Teacher


class TestTeacher(unittest.TestCase):
    """ Teacher unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeacher(self):
        """
        Test Teacher
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.teacher.Teacher()
        pass


if __name__ == '__main__':
    unittest.main()
