# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.score_api import ScoreApi


class TestScoreApi(unittest.TestCase):
    """ ScoreApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.score_api.ScoreApi()

    def tearDown(self):
        pass

    def test_add_score(self):
        """
        Test case for add_score

        Add new score
        """
        pass

    def test_delete_score(self):
        """
        Test case for delete_score

        Deletes a score
        """
        pass

    def test_get_score_by_id(self):
        """
        Test case for get_score_by_id

        Find Score by ID
        """
        pass

    def test_update_score(self):
        """
        Test case for update_score

        Update existing score
        """
        pass


if __name__ == '__main__':
    unittest.main()
