# coding: utf-8

"""
    Test_4_Success

    API for Test4Success

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.students_api import StudentsApi


class TestStudentsApi(unittest.TestCase):
    """ StudentsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.students_api.StudentsApi()

    def tearDown(self):
        pass

    def test_add_student(self):
        """
        Test case for add_student

        Add new student
        """
        pass

    def test_delete_student(self):
        """
        Test case for delete_student

        Deletes a student
        """
        pass

    def test_get_student_by_id(self):
        """
        Test case for get_student_by_id

        Find Student by ID
        """
        pass

    def test_update_student(self):
        """
        Test case for update_student

        Update existing student
        """
        pass


if __name__ == '__main__':
    unittest.main()
